from models import engine, db_session, Base, Department, Employee, Role, Form
from random import randrange
import datetime
from datetime import timedelta

Base.metadata.create_all(bind=engine)

# Departments 

engineering = Department(name='Engineering')
hr = Department(name='Human Resources')
production = Department(name='Production')
rd = Department(name='Research and Development')
marketing = Department(name='Marketing')
accounting = Department(name='Accounting')

db_session.add(engineering)
db_session.add(hr)
db_session.add(production)
db_session.add(rd)
db_session.add(marketing)
db_session.add(accounting)

# Roles
manager = Role(name='manager')
engineer = Role(name='engineer')
programmer = Role(name='programmer')
security = Role(name='security specialist')
data_admin = Role(name='database administrator')
marketing_manager = Role(name='marketing manager')
accountant = Role(name='accountant')
financial_advisor = Role(name='financial advisor')
admin_assis = Role(name='administrative assistant')
business_analyst = Role(name='business analyst')
office_manager = Role(name='office manager')
quality_control = Role(name='quality control')

db_session.add(manager)
db_session.add(engineer)
db_session.add(programmer)
db_session.add(security)
db_session.add(data_admin)
db_session.add(marketing_manager)
db_session.add(accountant)
db_session.add(financial_advisor)
db_session.add(admin_assis)
db_session.add(business_analyst)
db_session.add(office_manager)
db_session.add(quality_control)


# Employees
peter = Employee(name='Peter', department=engineering, role=engineer, sex='M')
roy = Employee(name='Roy', department=engineering, role=engineer, sex='M')
tracy = Employee(name='Tracy', department=hr, role=manager, sex='F')
addison = Employee(name='Addison', department=engineering, role=manager, sex='F')
ash = Employee(name='Ash', department=engineering, role=manager, sex='F')
dakota = Employee(name='Dakota', department=engineering, role=manager, sex='F')
eddie = Employee(name='Eddie', department=hr, role=manager, sex='F')
emerson = Employee(name='Emerson', department=hr, role=manager, sex='F')
glenn = Employee(name='Glenn', department=hr, role=manager, sex='F')
harper = Employee(name='Harper', department=production, role=manager, sex='F')
harley = Employee(name='Harley', department=production, role=engineer, sex='F')
gabriela = Employee(name='Gabriela', department=production, role=programmer, sex='F')
hudson = Employee(name='Hudson', department=production, role=programmer, sex='F')
james = Employee(name='James', department=production, role=programmer, sex='F')
jamie = Employee(name='Jamie', department=rd, role=programmer, sex='M')
jesse = Employee(name='Jesse', department=rd, role=security, sex='M')
jordan = Employee(name='Jordan', department=rd, role=security, sex='M')
karter = Employee(name='Karter', department=rd, role=data_admin, sex='M')
kennedy = Employee(name='Kennedy', department=rd, role=data_admin, sex='M')
logan = Employee(name='Logan', department=marketing, role=data_admin, sex='M')
mackenzie = Employee(name='Mackenzie', department=marketing, role=marketing_manager, sex='M')
parker = Employee(name='Parker', department=marketing, role=accountant, sex='M')
ray = Employee(name='Ray', department=marketing, role=financial_advisor, sex='M')
reese = Employee(name='Reese', department=accounting, role=admin_assis, sex='F')
remy = Employee(name='Remy', department=accounting, role=business_analyst, sex='F')
roan = Employee(name='Roan', department=accounting, role=office_manager, sex='F')
sam = Employee(name='Sam', department=accounting, role=quality_control, sex='F')

db_session.add(peter)
db_session.add(roy)
db_session.add(tracy)
db_session.add(addison)
db_session.add(ash)
db_session.add(dakota)
db_session.add(eddie)
db_session.add(emerson)
db_session.add(glenn)
db_session.add(harper)
db_session.add(harley)
db_session.add(gabriela)
db_session.add(hudson)
db_session.add(james)
db_session.add(jamie)
db_session.add(jesse)
db_session.add(jordan)
db_session.add(karter)
db_session.add(kennedy)
db_session.add(logan)
db_session.add(mackenzie)
db_session.add(parker)
db_session.add(ray)
db_session.add(reese)
db_session.add(remy)
db_session.add(roan)
db_session.add(sam)

def random_date():
	start = datetime.date(2017, 1, 1)
	end = datetime.date(2017, 11, 11)
	delta = end - start
	int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
	random_second = randrange(int_delta)
	return start + timedelta(seconds=random_second)

# Forms
form1 = Form(anonymous=True, statement='Example statement', created_by=peter, created_at=random_date(), against=roy)
form2 = Form(anonymous=True, statement='Example statement', created_by=roy, created_at=random_date(), against=peter)
form3 = Form(anonymous=True, statement='Example statement', created_by=tracy, created_at=random_date(), against=roy)
form4 = Form(anonymous=True, statement='Example statement', created_by=addison, created_at=random_date(), against=glenn)
form5 = Form(anonymous=True, statement='Example statement', created_by=dakota, created_at=random_date(), against=harley)
form6 = Form(anonymous=True, statement='Example statement', created_by=glenn, created_at=random_date(), against=gabriela)
form7 = Form(anonymous=True, statement='Example statement', created_by=gabriela, created_at=random_date(), against=addison)
form8 = Form(anonymous=True, statement='Example statement', created_by=james, created_at=random_date(), against=ash)
form9 = Form(anonymous=True, statement='Example statement', created_by=jordan, created_at=random_date(), against=tracy)
form10 = Form(anonymous=True, statement='Example statement', created_by=logan, created_at=random_date(), against=hudson)
form11 = Form(anonymous=True, statement='Example statement', created_by=parker, created_at=random_date(), against=roan)
form12 = Form(anonymous=True, statement='Example statement', created_by=remy, created_at=random_date(), against=sam)
form13 = Form(anonymous=True, statement='Example statement', created_by=gabriela, created_at=random_date(), against=eddie)
form14 = Form(anonymous=True, statement='Example statement', created_by=jesse, created_at=random_date(), against=sam)
form15 = Form(anonymous=True, statement='Example statement', created_by=kennedy, created_at=random_date(), against=logan)

db_session.add(form1)
db_session.add(form2)
db_session.add(form3)
db_session.add(form4)
db_session.add(form5)
db_session.add(form6)
db_session.add(form7)
db_session.add(form8)
db_session.add(form9)
db_session.add(form10)
db_session.add(form11)
db_session.add(form12)
db_session.add(form13)
db_session.add(form14)
db_session.add(form15)

db_session.commit()

